# Crazyflie Flight Configuration
connection:
  uri: "radio://0/88/2M/E7E7E7E7F0"
  cache_dir: "./cache"

flight:
  default_height: 0.5  # meters
  hover_height: 0.4    # meters
  default_velocity: 0.3  # m/s
  landing_velocity: 0.2  # m/s
  hover_duration: 5.0    # seconds
  controller: "MELLINGER"      # PID or MELLINGER

safety:
  max_flight_time: 30.0  # seconds - auto-land after this time
  battery_threshold: 3.2  # volts - emergency land below this
  connection_timeout: 5.0  # seconds - emergency land if connection lost
  emergency_land_velocity: 0.5  # m/s - fast emergency landing

logging:
  period_ms: 10  # milliseconds
  log_file: "./logs/flight_log.csv"
  variables:
    - "stateEstimate.x"
    - "stateEstimate.y" 
    - "stateEstimate.z"
    - "stabilizer.roll"
    - "stabilizer.pitch"
    - "stabilizer.yaw"
    - "pm.vbat"
